name: Test Container
on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/test-container.yml"
  workflow_dispatch:
    inputs:
      enable_linux_cross_windows:
        description: 'Enable linux cross windows build'
        type: boolean
        default: false
      enable_linux_cross_aarch64:
        description: 'Enable linux cross aarch64 build'
        type: boolean
        default: false

permissions:
  contents: read
  actions: write

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  test-linux-cross-windows:
    if: github.event_name == 'workflow_dispatch' && inputs.enable_linux_cross_windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: i686, crt: ucrt }
          - { arch: x86_64, crt: ucrt }
          - { arch: armv7, crt: ucrt }
          - { arch: aarch64, crt: ucrt }
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: ./install-dependencies.sh
      - uses: rui314/setup-mold@v1
      - name: Setup Debug Tools
        run: |
          sudo apt-get -qy install bat lsd fd-find btop
          sudo ln -s /usr/bin/batcat /usr/bin/bat
          sudo ln -s /usr/bin/fdfind /usr/bin/fd
      - name: Setup LLVM-MinGW
        run: |
          LLVM_MINGW_VER=20260311
          curl -LO "https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_VER/llvm-mingw-$LLVM_MINGW_VER-ucrt-ubuntu-22.04-x86_64.tar.xz"
          tar -Jxf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw* /opt/llvm-mingw
          echo /opt/llvm-mingw/bin >> $GITHUB_PATH
      - name: Build
        env:
          COMPILER_LAUNCHER: ccache
        run: |
          sudo apt-get update -qq && sudo apt-get install -qy ccache libltdl-dev swig autoconf-archive
          ./build-cross-tools.sh /opt/llvm-mingw $(pwd)/install/llvm-mingw ${{matrix.arch}} --with-zlib --with-zstd

  test-linux-cross-aarch64:
    if: github.event_name == 'workflow_dispatch' && inputs.enable_linux_cross_aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: ./install-dependencies.sh --with-arm64
      - uses: rui314/setup-mold@v1
      - name: Setup Debug Tools
        run: |
          sudo apt-get -qy install bat lsd fd-find btop
          sudo ln -s /usr/bin/batcat /usr/bin/bat
          sudo ln -s /usr/bin/fdfind /usr/bin/fd
      - name: Setup LLVM-MinGW
        run: |
          LLVM_MINGW_VER=20260311
          curl -LO "https://github.com/mstorsjo/llvm-mingw/releases/download/$LLVM_MINGW_VER/llvm-mingw-$LLVM_MINGW_VER-ucrt-ubuntu-22.04-x86_64.tar.xz"
          tar -Jxf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw* /opt/llvm-mingw
      - name: Build
        env:
          COMPILER_LAUNCHER: ccache
        run: |
          sudo apt-get update -qq && sudo apt-get install -qy ccache g++-aarch64-linux-gnu
          ./build-all.sh /opt/llvm-mingw --host=aarch64-linux-gnu --no-runtimes --llvm-only
      - name: Assemble the cross-built toolchain
        run: |
          sudo apt-get install -qy qemu-user-binfmt
          ./prepare-cross-toolchain-unix.sh /opt/llvm-mingw $(pwd)/install/llvm-mingw
      - name: Test using the cross-built assembled toolchain
        run: |
          sudo apt-get install -qy libc6-arm64-cross libstdc++6-arm64-cross
          QEMU_LD_PREFIX=/usr/aarch64-linux-gnu ./test-libcxx-module.sh $(pwd)/install/llvm-mingw
          QEMU_LD_PREFIX=/usr/aarch64-linux-gnu ./run-tests.sh $(pwd)/install/llvm-mingw

  install-latest-toolchains:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      - name: Setup apt sources
        run: |
          set -e
          echo "=================================="
          echo "cat /etc/apt/apt-mirrors.txt"
          cat /etc/apt/apt-mirrors.txt
          echo "=================================="
          echo "cat /etc/apt/sources.list.d/ubuntu.sources"
          cat /etc/apt/sources.list.d/ubuntu.sources
          echo "=================================="
          # sudo sed -i 's/noble/devel/g' /etc/apt/sources.list.d/ubuntu.sources
          # cat /etc/apt/sources.list.d/ubuntu.sources

          sudo rm -rf /etc/apt/apt-mirrors.txt
          sudo rm -rf /etc/apt/sources.list.d
          sudo tee /etc/apt/sources.list > /dev/null <<EOF
          deb [arch=amd64] https://archive.ubuntu.com/ubuntu/ devel main restricted universe multiverse
          deb [arch=amd64] https://archive.ubuntu.com/ubuntu/ devel-backports main restricted universe multiverse
          deb [arch=amd64] https://archive.ubuntu.com/ubuntu/ devel-proposed main restricted universe multiverse
          deb [arch=amd64] https://archive.ubuntu.com/ubuntu/ devel-security main restricted universe multiverse
          deb [arch=amd64] https://archive.ubuntu.com/ubuntu/ devel-updates main restricted universe multiverse
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/ devel main restricted universe multiverse
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/ devel-backports main restricted universe multiverse
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/ devel-proposed main restricted universe multiverse
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/ devel-security main restricted universe multiverse
          deb [arch=arm64] https://ports.ubuntu.com/ubuntu-ports/ devel-updates main restricted universe multiverse
          EOF
      - name: Install toolchains
        run: |
          set -e
          sudo dpkg --add-architecture arm64
          sudo apt-get update -qq
          sudo apt-get install -qqy -o Dpkg::Use-Pty=0 \
            lsd \
            gcc g++ clang \
            zlib1g-dev:arm64 libzstd-dev:arm64
      - name: Verify toolchains
        run: |
          set -e
          echo "=================================="
          lsd -lL /usr/bin/gcc
          gcc --version
          echo "=================================="
          gcc -v
          echo
          echo "=================================="
          lsd -lL /usr/bin/g++
          g++ --version
          echo "=================================="
          g++ -v
          echo
          echo "=================================="
          lsd -lL /usr/bin/clang
          clang --version
          echo
          echo "=================================="
          lsd -l /usr/lib/aarch64-linux-gnu/libz.*
          echo "=================================="
          lsd -l /usr/lib/aarch64-linux-gnu/libzstd.*

  upload-multiple-artifacts-at-once:
    runs-on: ubuntu-latest
    steps:
      - name: Create test artifacts
        run: |
          echo "Hello, world!" > hello_1.txt
          echo "Hello, world!" > hello_2.txt
          echo "Hello, world!" > hello_3.txt
      - uses: llvm-latest/github-script-with-artifact@main
        with:
          script: |
            const fs = require('fs');
            const files = fs.readdirSync('.').filter(file => file.endsWith('.txt'));
            for (const file of files) {
                core.info(`>>> Uploading ${file}...`);
                const uploadResponse = await artifact.uploadArtifact(
                    file,   // Name
                    [file], // Files
                    '.',    // Root Directory
                    { compressionLevel: 0 }
                );
            }

  test-docker-linux-cross-aarch64:
    if: false
    runs-on: ubuntu-latest
    container:
      image: ubuntu:devel
      options: --privileged
    steps:
      - name: Install Docker
        run: |
          apt-get update -qq && apt-get install -qqy docker.io
      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          image: tonistiigi/binfmt
          cache-image: false
      - uses: actions/checkout@v6
      - name: Test using the cross-built assembled toolchain
        run: |
          mount -t binfmt_misc none /proc/sys/fs/binfmt_misc
          echo "ls /proc/sys/fs/binfmt_misc"
          echo "=================================="
          ls /proc/sys/fs/binfmt_misc
          echo "=================================="

          apt-get install -qqy make curl zip unzip bzip2 xz-utils > /dev/null
          LINUX_AARCH64_MINGW="https://github.com/mstorsjo/llvm-mingw/releases/download/20260116/llvm-mingw-20260116-ucrt-ubuntu-22.04-aarch64.tar.xz"
          curl --retry 3 --retry-delay 5 --retry-all-errors -fSLO "$LINUX_AARCH64_MINGW"
          tar -Jxf llvm-mingw-*.tar.xz
          rm llvm-mingw-*.tar.xz
          mv llvm-mingw* /opt/llvm-mingw

          apt-get install -qqy qemu-user-binfmt libc6-arm64-cross libstdc++6-arm64-cross
          QEMU_LD_PREFIX=/usr/aarch64-linux-gnu ./test-libcxx-module.sh /opt/llvm-mingw
          QEMU_LD_PREFIX=/usr/aarch64-linux-gnu ./run-tests.sh /opt/llvm-mingw
